# Generated by Django 5.0.6 on 2024-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskManager_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="important",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("hot", "Hot")],
                default="low",
                max_length=25,
            ),
        ),
    ]
