# Generated by Django 5.0.6 on 2024-06-06 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
