# Generated by Django 5.0.2 on 2024-03-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"verbose_name": "WatchList", "verbose_name_plural": "WatchLists"},
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_list",
                to="apis.streamplatform",
            ),
        ),
    ]
